### PR TITLE
simclist: handle faults during memory allocation

### PR DESCRIPTION
**Pull request by frankmorgner**
fixes several situations that cause segmentation faults

### CODE REVIEW

**Comment by LudovicRousseau** [comment]
``strlcat()`` and ``strlcpy()`` are *not* used in PCSC.
Why do you need to add a check in ``configure.ac``?

**Comment by frankmorgner** [comment]
I just noticed the use of `HAVE_STRLCAT` in `strlcpycat.h`. If the two functions are not used, then this header file and its implementation should be removed accordingly.

**Comment by LudovicRousseau** [comment]
``strlcat()`` is now used only by the CCID driver.
For historical reasons the file was provided in pcsc-lite source code.

**Comment by frankmorgner** [comment]
I think it would be best to move the files from pcsc-lite to ccid. I'll remove the commit from this PR.

**Comment by LudovicRousseau** [comment]
Committed in https://github.com/LudovicRousseau/PCSC/commit/a801c6e613fde89c09c755a20003ab82fd6a5c47

Thanks and sorry for the delay.

**Pull request closed without merging**
