### PR TITLE
Fixed compilation on OS X

### PR DESCRIPTION
**Pull request by frankmorgner**
... and I think FreeBSD in general.

### CODE REVIEW

**Comment by LudovicRousseau** [comment]
What are the errors you are trying to solve?

**Comment by frankmorgner** [comment]
Compilation errors, basically:

1. `LONG` is an `int`, which contradicts the definition of the functions interface if `LOG` is not defined.
2. You need to check for `strlcpy` and `strlcat` in order to have `HAVE_STRLCPY`/`HAVE_STRLCAT` defined in `config.h`. Those defines are used in `strlcpycat.h`

**Comment by LudovicRousseau** [comment]
Your patch fixes warnings and not errors. Exact?

PCSC is not supposed to be used on Mac OS X.

**Comment by frankmorgner** [comment]
No, these are errors, not warnings.

1. Trying to compile with `-DNO_LOG` on any platform will fail!
2. Try to compile on a platform that implements strlcpy and strlcat should fail (i.e. FreeBSD or OS X)!  I tested the code on Mac.

**Comment by LudovicRousseau** [comment]
Using ``-DNO_LOG`` make the compilation fail on Mac OS X.
```
error.c:53:16: error: conflicting types for 'pcsc_stringify_error'
PCSC_API char* pcsc_stringify_error(const long pcscError)
               ^
../src/PCSC/pcsclite.h:237:7: note: previous declaration is here
char *pcsc_stringify_error(const LONG);
      ^
```
But it works correctly on Debian GNU/Linux.
What is your target system?

And I have no problem with strlcpy and strlcat on Mac OS X.

**Comment by frankmorgner** [comment]
Sorry, I don't have the time to dig deeper into this. But if you have two different definitions of pcsc_stringify_error in the same file, it's obviously a problem. If you are using `HAVE_STRLCAT`,which is typically generated from autoconf, without looking for it with an autoconf macro, it's obviously a problem.

I just wanted to contribute back my findings. I am totally fine if you choose not to integrate this.

**Comment by LudovicRousseau** [comment]
NO_LOG issue fixed in e2752b7b26b0fc6cbee5f66be501396245cefee1

pcsclite do not use strlcpy and strlcat anymore (see afc3f76e068628d8aafb2f153ef80d6fe73b387b). So there is nothing to fix.

**Pull request closed without merging**
