### PR TITLE
SCardCancel() still not terminating SCardGetStatusChange() call...

### PR DESCRIPTION
**Pull request by llogar**
Commit 7a3738d2f8e48c669b0e3f485cb9dcabeffc941a is supposed to fix SCardCancel() not terminating SCardGetStatusChange() call.

However at least strongSwan still hangs on exit due to this bug. This commit appears to fix this...

### CODE REVIEW

**Comment by LudovicRousseau** [comment]
What PKCS#11 library are you using with StronSwan?

**Comment by llogar** [comment]
opensc-pkcs11.so (compiled from rev. b7de5888a0d9012c99e5f624bab1b98671fc7446) with some patches here and there...

**Comment by LudovicRousseau** [comment]
I propose to use this OpenSC patch: [patch.txt](https://github.com/LudovicRousseau/PCSC/files/1333302/patch.txt)

**Comment by llogar** [comment]
I've tried your patch, but strongSwan now hangs during C_Sign() too, not just on exit...

**Comment by LudovicRousseau** [comment]
The pcsc-lite documentation says that "SCardCancel() MUST be called with the same SCARDCONTEXT as SCardGetStatusChange()."
https://pcsclite.alioth.debian.org/api/group__API.html#gaacbbc0c6d6c0cbbeb4f4debf6fbeeee6

OpenSC has specific code to use a **different** context because that was how pcsc-lite used to work.

I don't know what the problem is with C_Sign().
I think you should open a bug at OpenSC since it is more a problem with OpenSC not using the (fixed) PC/SC API correctly.

**Comment by llogar** [comment]
Ok, here is what's happening now (with your patch applied):

Thread A establishes context, connects to card, then waits for status change event.
```
SCardEstablishContext(...)
SCardConnect(...)
SCardGetStatusChange(INFINITE)
```

Thread B wants to send some data (C_Sign() function) using the _hCard_ handle from thread A...
```
SCardBeginTransaction(handle from SCardConnect from thread A )
```
...and hangs
 
I guess this is a strongSwan issue/bug now. Thanks anyway.

**Comment by LudovicRousseau** [comment]
Exact. Two different threads need to use two different PC/SC contexts and so also 2 different card context.

https://pcsclite.alioth.debian.org/api/group__API.html#gaa1b8970169fd4883a6dc4a8f43f19b67
" Each thread of an application shall use its own SCARDCONTEXT, unless calling SCardCancel(), which MUST be called with the same context as the context used to call SCardGetStatusChange(). "

**Comment by LudovicRousseau** [comment]
The problem was in OpenSC.

**Pull request closed without merging**
