### PR TITLE
Removing usage of function chmod - race condition possibility; CWE-362

### PR DESCRIPTION
**Pull request by vegaMato**

### CODE REVIEW

**Comment by LudovicRousseau** [comment]
What happened?

**Comment by vegaMato** [comment]
Hi Ludovic,

I am member of a team analyzing your project for security bugs for the course of Secure coding principles and practicies lead by doctor Peter Svenda at Faculty of Informatics, MU Brno.

We have found some bugs and currenlty we are writing fixies for them, this pull request was a typo and I need to wait for my collaborators and their fix commits.  I have also repository with notes and list of analysis we did, when all of us push their results I&#39;ll send you a link if you want.

BR,
Martin Frian.

**Comment by LudovicRousseau** [comment]
I think I found it at https://github.com/vegaMato/PA193_project_tasks
Nice work.

The Coverity results are available at https://scan.coverity.com/projects/pcsc-lite?tab=overview but i think you do not have access.

**Comment by LudovicRousseau** [comment]
I need your email to invite you to Coverity

**Comment by vegaMato** [comment]
localhost@azet.sk

**Pull request closed without merging**
